import { useMemo, useState } from 'react'
import './App.css'

const sampleResume = `Nitin Reddy\nB.Tech Computer Science\nSkills: Java, Spring Boot, React, JavaScript, SQL, MySQL, Git, AWS\nExperience: Built full-stack web applications and REST APIs.`
const sampleJob = `Looking for a Software Engineer with Java, Spring Boot, React, SQL, REST API, Git and AWS experience.`
const api = import.meta.env.VITE_API_URL || 'http://localhost:8080'

export default function App() {
 const [resume,setResume]=useState(sampleResume),[jobDescription,setJobDescription]=useState(sampleJob),[result,setResult]=useState(null),[batch,setBatch]=useState(null),[files,setFiles]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
 async function analyze(){setLoading(true);setError('');try{let r=await fetch(api+'/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resume,jobDescription})});if(!r.ok)throw Error('Analysis service unavailable');setResult(await r.json())}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function analyzeBatch(){if(!files.length){setError('Choose at least one PDF or text resume.');return}setLoading(true);setError('');try{let data=new FormData();files.forEach(f=>data.append('files',f));data.append('jobDescription',jobDescription);let r=await fetch(api+'/api/candidates/batch',{method:'POST',body:data});let json=await r.json();if(!r.ok)throw Error(json.message||'Batch analysis failed');setBatch(json)}catch(e){setError(e.message)}finally{setLoading(false)}}
 const ring=useMemo(()=>({'--score':result?.score||0}),[result])
 return <main><section className="hero"><div className="brand"><span className="mark">R</span> ResumeReviewer <small>AI SCREENING STUDIO</small></div><div className="hero-grid"><div><p className="eyebrow">DECISION INTELLIGENCE FOR HIRING</p><h1>Find the signal.<br/><em>Not just the keywords.</em></h1><p className="subtitle">A focused screening workspace that turns resumes and job descriptions into explainable hiring insights.</p></div><div className="stat-card"><span>SCREENING ENGINE</span><strong>Explainable matching</strong><p>Skills, experience and education signals—summarized in one focused review.</p><div className="pulse"><i/> Ready to analyze</div></div></div></section>
 <section className="workspace"><div className="input-card"><div className="card-head"><span>01</span><h2>Candidate profile</h2></div><textarea value={resume} onChange={e=>setResume(e.target.value)}/><p>Paste resume text for a single-candidate review.</p></div><div className="input-card"><div className="card-head"><span>02</span><h2>Role requirements</h2></div><textarea value={jobDescription} onChange={e=>setJobDescription(e.target.value)}/><p>Include responsibilities, required skills and preferred qualifications.</p></div><button className="analyze" onClick={analyze} disabled={loading}>{loading?'Analyzing signals...':'Analyze candidate'} <b>→</b></button>{error&&<div className="error">{error}</div>}</section>
 <section className="batch-zone"><div><p className="eyebrow">MULTI-CANDIDATE MODE</p><h2>Rank an entire candidate pool.</h2><p>Upload multiple PDF or text resumes and receive an ordered shortlist.</p></div><label className="upload"><input type="file" multiple accept=".pdf,.txt" onChange={e=>setFiles([...e.target.files])}/><strong>{files.length?files.length+' resumes selected':'Choose resumes'}</strong><span>PDF or TXT · multiple files supported</span></label><button className="batch-btn" onClick={analyzeBatch} disabled={loading}>{loading?'Ranking candidates...':'Build shortlist'}</button></section>
 {result&&<section className="results"><div className="result-top"><div><p className="eyebrow">SCREENING RESULT</p><h2>{result.candidate}</h2><p>{result.summary}</p></div><div className="score" style={ring}><div><strong>{result.score}</strong><span>/100</span></div></div></div><div className="recommendation"><span>Recommendation</span><strong>{result.recommendation}</strong><p>Experience: {result.experience} · {result.educationDetected}</p></div><div className="signal-grid"><Signal title="Matched signals" items={result.matchedSkills} type="good"/><Signal title="Potential gaps" items={result.missingSkills} type="gap"/><Signal title="Resume inventory" items={result.extractedSkills} type="neutral"/></div></section>}
 {batch&&<section className="ranking"><div className="ranking-head"><div><p className="eyebrow">SHORTLIST</p><h2>{batch.shortlisted} of {batch.total} candidates recommended</h2></div><span>Sorted by compatibility score</span></div>{batch.candidates.map((c,i)=><article className="candidate" key={c.id}><div className="rank">{String(i+1).padStart(2,'0')}</div><div className="candidate-name"><strong>{c.name}</strong><small>{c.experience} · {c.educationDetected}</small></div><div className="mini-chips">{c.matchedSkills.slice(0,4).map(s=><span key={s}>{s}</span>)}</div><div className="candidate-score"><strong>{c.score}</strong><span>{c.recommendation}</span></div></article>)}</section>}
 <footer>ResumeReviewer · React + Java Spring Boot · Explainable candidate intelligence</footer></main>
}
function Signal({title,items=[],type}){return <article className={'signal '+type}><h3>{title}</h3><div className="chips">{items.length?items.map(x=><span key={x}>{x}</span>):<p>No signals detected</p>}</div></article>}
